exclude: |
  (?x)
  /static/description/index\.html$|
  .*\.(diff|patch)$|
  /static/(src/)?lib/|
  (LICENSE.*|COPYING.*)
default_language_version:
  python: python3
  node: "14.14.0"
repos:
  - repo: local
    hooks:
      - id: forbidden-files
        name: forbidden files
        entry: found forbidden files; remove them
        language: fail
        files: "\\.rej$"
  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --expand-star-imports
          - --ignore-init-module-imports
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args:
          - --line-length=100
        additional_dependencies: ["click<8.1.0"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args:
          - --keep-percent-format
  - repo: https://github.com/timothycrosley/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort except __init__.py
        args: [--settings, .]
        exclude: /__init__\.py$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier + plugin-xml
        additional_dependencies:
          # HACK https://github.com/prettier/pre-commit/issues/16#issuecomment-713474520
          - prettier@2.1.2
          - "@prettier/plugin-xml@0.12.0"
        args:
          - --plugin=@prettier/plugin-xml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0 # Обновленная версия flake8
    hooks:
      - id: flake8
        name: flake8 except __init__.py
        exclude: ^(__init__\.py|__manifest__.py)$
        additional_dependencies: ["flake8-bugbear==23.3.12"] # Обновленная версия flake8-bugbear
        args: ["--max-line-length=100"]
      - id: flake8
        name: flake8 only __init__.py
        args: ["--extend-ignore=F401"] # ignore unused imports in __init__.py
        files: /__init__\.py$
        additional_dependencies: ["flake8-bugbear==23.3.12"] # Обновленная версия flake8-bugbear
